name: Cleanup Resources

on:
  workflow_run:
    workflows: ["Terraform Workflow"]
    types:
      - completed

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: latest # Use the latest Terraform version

    - name: Initialize Terraform
      run: terraform init

    - name: Destroy Terraform Resources
      run: terraform destroy -auto-approve
